document.writeln("<div class=\'head\'>");
document.writeln("<div class=\'head_con\'>");
document.writeln("<div class=\'register font_s14\'>");
document.writeln("<span class=\'tel\'><img src=\'/rsr_images/tel.png\' width=\'14\' height=\'14\' alt=\'人事人联系电话\'/> 400-888-0556</span>");
document.writeln("<a href=\'http://hcm.renshiren.com/rsr/login.jsp' title=\'登录\'>登录</a>");
document.writeln("<a href=\'http://hcm.renshiren.com/rsr/register.jsp' title=\'注册\'>注册</a>");
document.writeln("</div>");
document.writeln("<div class=\'nav clear\'>");
document.writeln("<h1><a title=\'人事人科技改变人力资源\' href=\'http://www.renshiren.com\' class=\'rsr_logo clear\'><img src=\'/rsr_images/logo.png\' width=\'106\' height=\'39\' alt=\'人事人(北京)科技有限公司\'/><i><font>科技改变人力资源</font><br/><font class=\'rsr_web\'>renshiren.com</font></i></a></h1>");
document.writeln("<div class=\'nav_con\'>");
document.writeln("<ul>");
document.writeln("<li><a href=\'index.html\' title=\'首页\' class=\'home\'>首页</a></li>");
document.writeln("<li><a href=\'hcm.html\' title=\'人事人HCM\'>人事人HCM</a></li>");
document.writeln("<li class=\'m border_none\'><a href=\'javascript:;\' title=\'服务项目\' class=\'select_on\'>服务项目</a>");
document.writeln("<em class=\'point\'><img src=\'/rsr_images/point.png\' width=\'10\' height=\'5\'/> </em>");
document.writeln("<p class=\'nav_son\'>");
document.writeln("<a href=\'enterprise_payment.html\' title=\'\' class=\'service_p1\'>企业社保代理</a>");
document.writeln("<a href=\'personal_payment.html\' title=\'\' class=\'service_p2\'>个人社保代理</a>");
document.writeln("<a href=\'recruit.html\' title=\'灵活用工保\' class=\'service_p9\'>灵活用工保</a>");
document.writeln("<a href=\'bpo.html\' title=\'\' class=\'service_p3\'>BPO<sup>+</sup></a>");
document.writeln("<a href=\'service_project.html\' title=\'\' class=\'service_p4\'>福利<sup>+</sup></a>");
document.writeln("<a href=\'saas.html\' title=\'\' class=\'service_p5\'>薪云</a>");
document.writeln("<a href=\'sharehr.html\' title=\'共享HR\' class=\'service_p8\'>共享HR</a>");
document.writeln("<a href=\'http://qichengbao.renshiren.com\' title=\'企成宝\' class=\'service_p7\'>企成宝</a>");
document.writeln("</p>");
document.writeln("</li>");
document.writeln(" <li class=\'m border_none\'>");
document.writeln("<a href=\'javascript:;\' title=\'解决方案\' class=\'select_solu\'>解决方案</a>");
document.writeln("<em class=\'point\'><img src=\'/rsr_images/point.png\' width=\'10\' height=\'5\'/></em>");
document.writeln("<p class=\'nav_son nav_son_solu\'>");
document.writeln("<a href=\'repast.html\' title=\'餐饮行业\' class=\'solu_p1\'>餐饮行业</a>");
document.writeln("<a href=\'commerce.html\' title=\'电商商业\' class=\'solu_p2\'>电商行业</a>");
document.writeln("</p>");
document.writeln("</li>");
document.writeln("<li><a href=\'service_support.html\' title=\'服务支持\'>服务支持</a></li>");
document.writeln("<li class=\'m margin_l border_none on\'>");
document.writeln("<a href=\'javascript:;\' title=\'关于人事人\' class=\'select_about\'>关于人事人</a>");
document.writeln("<em class=\'point\'><img src=\'/rsr_images/point.png\' width=\'10\' height=\'5\'/></em>");
document.writeln("<p class=\'nav_son nav_son_about\'>");
document.writeln("<a href=\'about.html\' title=\'\' class=\'rsr_about1\'>人事人介绍</a>");
document.writeln("<a href=\'expert.html\' title=\'\' class=\'rsr_about7\'>专家顾问</a>");
document.writeln("<a href=\'marketing_list.html\' title=\'\' class=\'rsr_about6\'>市场活动</a>");
document.writeln("<a href=\'dynamic_list.html\' title=\'\' class=\'rsr_about5\'>人资问答</a>");
document.writeln("<a href=\'media_list.html\' title=\'\' class=\'rsr_about4\'>媒体报道</a>");
document.writeln("</p>");
document.writeln("</li>");
document.writeln("</ul>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");