document.writeln("<div class=\'footer\'>");
document.writeln("<div class=\'foot\'>");
document.writeln("<strong>人事人</strong> — 科技改变人力资源");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'footer_con\'>");
document.writeln("<div class=\'address clear\'>");
document.writeln("<div class=\'add_l\'>");
document.writeln("<p>人事人集团</p>");
document.writeln("<div class=\"add_title slideQTxtBox\">");
document.writeln("<ul class=\"clear hd\">");
document.writeln("<li id=\"one1\" class=\"on\" onmouseover=\"setTab(\'one\',1,9)\" ><a title=\"北京\" href=\"javascript:;\">北京</a></li>");
document.writeln("<li id=\"one2\" onmouseover=\"setTab(\'one\',2,9)\" ><a title=\"天津\" href=\"javascript:;\">天津</a></li>");
document.writeln("<li id=\"one3\" class=\"\" onmouseover=\"setTab(\'one\',3,9)\"><a title=\"上海\" href=\"javascript:;\">上海</a></li>");
document.writeln("<li id=\"one4\"  onmouseover=\"setTab(\'one\',4,9)\"><a title=\"杭州\" href=\"javascript:;\">杭州</a></li>");
document.writeln("<li id=\"one5\"  onmouseover=\"setTab(\'one\',5,9)\"><a title=\"宁波\" href=\"javascript:;\">宁波</a></li>");
document.writeln("<li id=\"one6\"  onmouseover=\"setTab(\'one\',6,9)\"><a title=\"广州\" href=\"javascript:;\">广州</a></li>");
document.writeln("<li id=\"one7\" onmouseover=\"setTab(\'one\',7,9)\"><a title=\"南京\" href=\"javascript:;\">南京</a></li>");
document.writeln("<li id=\"one8\" onmouseover=\"setTab(\'one\',8,9)\"><a title=\"石家庄\" href=\"javascript:;\">石家庄</a></li>");
document.writeln("<li id=\"one9\" onmouseover=\"setTab(\'one\',9,9)\"><a title=\"深圳\" href=\"javascript:;\">深圳</a></li>");
document.writeln("</ul>");
document.writeln(" <div class=\'bd\'>");
document.writeln("<div class=\"add_con\"  id=\"con_one_1\">");
// document.writeln("<p>人事人（北京）科技有限公司（总部）<br/>地址：北京市朝阳区建国路88号SOHO现代城B座1604</p>");
// document.writeln("<p>北京中锐博远人力资源顾问有限公司 <br/>地址：北京市朝阳区建国路88号SOHO现代城B座1605</p>");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_2\">");
document.writeln("<p>人事人（天津）科技有限公司<br/>地址：天津市汽车产业园云景道1号汽车大厦805</p>");
document.writeln("<p>天津市南开区鞍山西道286号启航大厦18层1812-1816</p>");
document.writeln("");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_3\">");
document.writeln("<p>上海力晖人力资源管理有限公司<br/>地址：上海市静安区天目西路218号嘉里不夜城一座1709</p>");
/*document.writeln("<p>上海锐播企业管理顾问有限公司<br/>地址：上海市闸北区恒通路360号一天下大厦19C10室</p>");*/
document.writeln("");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_4\">");
document.writeln("<p>杭州欧凯人力资源管理有限公司<br/>地址：杭州市西湖区万塘路252号计量大厦11层1108-1112</p>");
document.writeln("");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_5\">");
document.writeln("<p>杭州欧凯人力资源管理有限公司宁波分公司<br/>地址：浙江省宁波市高新区江南路599号科技大厦四层406室</p>");
document.writeln("<p>浙江薪云信息技术有限公司 <br/>地址：宁波市鄞州区宁穿路1811号金融硅谷8号楼2107室</p>");
document.writeln("");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_6\">");
document.writeln("<p>北京中锐博远人力资源顾问有限公司广州分公司<br/>地址：广州市天河区河北路559号太平洋保险大厦2301</p>");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_7\">");
document.writeln("<p>杭州欧凯人力资源管理有限公司南京分公司 <br/>地址：江苏省南京市建邺区庐山路158号嘉业国际城2幢1903室</p>");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_8\">");
document.writeln("<p>石家庄力晖人力资源服务有限公司<br/>地址：河北省石家庄市长安区广安街15号官鲤公寓1号2号公寓式酒店1-1501</p>");
document.writeln("</div>");
document.writeln("<div class=\"add_con\" style=\"display: none\"  id=\"con_one_9\">");
document.writeln("<p>人事人（深圳）科技有限公司<br/>地址：深圳市福田区莲花街道福中社区深南大道2008号中国凤凰大厦2号楼25D</p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\"add_r\">");
document.writeln("<dl class=\"server\">");
document.writeln("<dt>服务</dt>");
document.writeln("<dd><a href=\"recruitment.html\" title=\"加入我们\">加入我们</a></dd>");
document.writeln("<dd><a href=\"about.html\" title=\"全国服务网络\">全国服务网络</a></dd>");
document.writeln("<dd><a href=\"privacy.html\" title=\"用户协议\">用户协议</a></dd>");
document.writeln("<dd><a href=\"javascript:;\" title=\"反馈\" class=\"feedback\">反馈</a></dd>");
document.writeln("</dl>");
document.writeln("<dl class=\"teamwork\">");
document.writeln("<dt>市场商务合作</dt>");
document.writeln("<dd>座机：010-85806807转8038</dd>");
document.writeln("<dd>Email：<a href=\"mailto:service@renshiren.com\">service@renshiren.com</a></dd>");
document.writeln("<dd class=\"qr_code\">");
document.writeln("<a href=\"javascript:;\" title=\"微信二维码\"><img src=\"rsr_images/weixin.png\" alt=\"人事人微信\" width=\"80\" height=\"80\"/><br/>微信二维码</a>");
document.writeln("<a href=\"javascript:;\" title=\"微博二维码\" class=\"\"><img src=\"rsr_images/weibo.png\" alt=\"人事人微博\" width=\"80\" height=\"80\"/><br/>微博二维码</a>");
document.writeln("<a href=\"javascript:;\" title=\"商务合作\" class=\"e_webo\"><img src=\"rsr_images/rsr_swhz.jpg\" alt=\"商务合作\" width=\"80\" height=\"80\"/><br/>商务合作</a>");
document.writeln("</dd>");
document.writeln("</dl>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<p class=\"sitemap\">");
document.writeln("<a href=\"sitemap.html\" title=\"站点地图\" target=\"_blank\">站点地图</a>");
document.writeln("<a href=\"sitemap.xml\" title=\"网站地图\" target=\"_blank\">网站地图</a>");
document.writeln("</p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'link\'>");
document.writeln("<div class=\'link_con clear\'>");
document.writeln("<span><a title=\'友情链接\'>友情链接：</a></span>");
document.writeln("<p>");
document.writeln("<a href=\'http://www.hxrs.gov.cn/\' title=\'人力资源和社会保障局\' target=\'_blank\' rel=\'nofollow\'>人力资源和社会保障局</a>");
document.writeln("<a href=\'http://www.chinahrm.net/\' title=\'中国人力资源管理网\' target=\'_blank\' rel=\'nofollow\'>中国人力资源管理网</a>");
document.writeln("<a href=\'http://www.bjrbj.gov.cn/\' title=\'北京市人力资源和社会保障局\' target=\'_blank\'  rel=\'nofollow\'>北京市人力资源和社会保障局</a>");
document.writeln("<a href=\'http://www.zjhz.lss.gov.cn/?39605624142662\' title=\'杭州市人力资源和社会保障网\' target=\'_blank\' rel=\'nofollow\'>杭州市人力资源和社会保障网</a>");
document.writeln("<a href=\'http://www.hroot.com/\' title=\'HRoot\' target=\'_blank\' rel=\'nofollow\'>HRoot</a>");
document.writeln("<a href=\'http://www.hrbar.com/default.htm\' title=\'HRbar\' target=\'_blank\' rel=\'nofollow\'>HRbar</a>");
document.writeln("<a href=\'http://www.tj.hrss.gov.cn/ecdomain/framework/tj/index.jsp\' title=\'天津市人力资源和社会保障局\' target=\'_blank\' rel=\'nofollow\'>天津市人力资源和社会保障局</a>");
// document.writeln("<a href=\'http://www.gongsibao.com\' title=\'公司宝\' target=\'_blank\' rel=\'nofollow\'>公司宝</a>");
// document.writeln("<a href=\'http://www.davdian.com\' title=\'大V店\' target=\'_blank\' rel=\'nofollow\'>大V店</a>");
document.writeln("<a href=\'http://www.lyvh.com\' title=\'耒阳人才\' target=\'_blank\' rel=\'nofollow\'>耒阳人才</a>");
document.writeln("<a href=\'https://m.kuaidi100.com\' title=\'快递查询\' target=\'_blank\' rel=\'nofollow\'>快递查询</a>");
document.writeln("</p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'copy\'>");
document.writeln("<div class=\'copy_con\'>");
document.writeln("Copyright © 2015-2018 人事人（北京）科技有限公司(www.renshiren.com) 京ICP备15067691号");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'feed_back\'>");
document.writeln("<div class=\'back_con\'>");
document.writeln("<div class=\'tt\'>");
document.writeln("<P>建议反馈</P>");
document.writeln("<a class=\'close_box\'>×</a>");
document.writeln("</div>");
document.writeln("<div class=\'tt_con clear\'>");
document.writeln("<p>");
document.writeln("终于等到你，很高兴为您服务，您可以通过以下方式联系我们");
document.writeln("</p>");
document.writeln("<p><strong>北京服务中心</strong></p>");
document.writeln("<p>地址:北京市朝阳区建国路88号SOHO现代城B座1604</p>");
document.writeln("<p>电话: 400-888-0556</p>");
document.writeln("<p>Email: <a href=\'mailto:service@renshiren.com\' target=\'_blank\' class=\'e_Email\'>service@renshiren.com</a></p>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("");
document.writeln("<script type=\"text/javascript\">");
document.writeln("function setTab(name,cursel,n){");
document.writeln("for(i=1;i<=n;i++){");
document.writeln("var menu=document.getElementById(name+i);");
document.writeln("var con=document.getElementById(\"con_\"+name+\"_\"+i);");
document.writeln("menu.className=i==cursel?\"on\":\"\";");
document.writeln("con.style.display=i==cursel?\"block\":\"none\";");
document.writeln("}");
document.writeln("};");
document.writeln("</script>");